create table car (id int8 generated by default as identity, brand varchar(20), color varchar(255), engine_number varchar(255), model varchar(255), passenger_car boolean, registration_number varchar(255), depot_id int8, driver_tribe_number int8, primary key (id));
-- create table car_value (car_id int8 not null, entry_date date, gross_value int4 not null, planned_end_of_life date, price_end_of_life int4 not null, primary key (car_id));
-- create table depot (id int8 generated by default as identity, address varchar(255), depot_name varchar(255), primary key (id));
-- create table driver (tribe_number int8 not null, birth_date date, mother_name varchar(50), name varchar(50), primary key (tribe_number));
-- alter table if exists car add constraint FK8safc29x608dhh8qq8pha26wb foreign key (depot_id) references depot;
-- alter table if exists car add constraint FKneb2rqyivfghtm8anaag53k20 foreign key (driver_tribe_number) references driver;
-- alter table if exists car_value add constraint FKkb7opreo5nfapgl5wlorngkm7 foreign key (car_id) references car;