package com.codecool.vizsgaremek_v1.entity;

public enum Brand {
    TESLA, MAZDA, BMW, SUBARU, PORSCHE, HONDA, LEXUS, TOYOTA, CHRYSLER, BUICK, HYUNDAI,
    AUDI, NISSAN, DODGE, GENESIS, MINI, VOLKSWAGEN, KIA, VOLVO, MERCEDES_BENZ,
    CADILLAC, CHEVROLET, FORD, GMC, JAGUAR, LINCOLN, JEEP, MITSUBISHI, LAND_ROVER,
    ALFA_ROMEO,
}

